dev:
  propel:
    param:
      classname:  DebugPDO

test:
  propel:
    param:
      classname:  DebugPDO

all:
  propel:
    class:        sfPropelDatabase
    param:
      classname:  PropelPDO
      dsn:        mysql:dbname=tjswebin_blog;host=localhost
      username:   tjswebin_tjs
      password:   escape
      encoding:   utf8
      persistent: true
      pooling:    true